version: '3.3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=nova
      - POSTGRES_PASSWORD=L4Bnova
      - POSTGRES_DB=nova_db
    ports:
      - "5433:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=webservices@labnova.com.mx
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"

